## =====================================================================
## 17_clusterability_tests_mice_strict.R
## Discreteness / clusterability tests for the EHR audit MICE primary 33-feature space.
##
## Strict MICE version:
##   - Requires output/model/X_primary33_std_mice.rds generated by
##     23_mice_primary_pooling_v2_fixed.R or 23c_save_mice_matrix_labels.R.
##   - Does NOT fall back to median-imputed reconstruction from final_full.
##   - Writes provenance/audit files so manuscript results cannot be confused
##     with the older median matrix X_primary33_std.rds.
## =====================================================================
source("00_paths.R")
suppressPackageStartupMessages({
  need <- c("data.table", "cluster", "diptest", "MASS")
  for (p in need) if (!requireNamespace(p, quietly = TRUE)) {
    install.packages(p, repos = "https://cloud.r-project.org")
  }
  library(data.table)
  library(cluster)
  library(diptest)
  library(MASS)
})
set.seed(20240601)

## ---------------- config ----------------
MANUAL_FEATURES33 <- c(
  "bilirubin_total_max", "alt_max", "pao2fio2ratio_min", "abs_lymphocytes_min",
  "lactate_max", "ph_min", "pco2_max", "calcium_min", "calcium_max", "ptt_max",
  "inr_max", "temperature_min", "temperature_max", "urine_output_24h_ml", "glucose_max",
  "aniongap_max", "potassium_min", "potassium_max", "hemoglobin_min", "sodium_min",
  "sodium_max", "wbc_max", "platelets_min", "bicarbonate_min", "chloride_min",
  "chloride_max", "bun_max", "creatinine_max", "resp_rate_max", "gcs_min",
  "spo2_min", "heart_rate_max", "mbp_min"
)

load_primary_features <- function() {
  fset_path <- file.path(DIR_MODEL, "feature_sets.rds")
  if (file.exists(fset_path)) {
    fs <- readRDS(fset_path)
    if (!is.null(fs$primary) && length(fs$primary) == 33L) {
      message("Using authoritative feature_sets.rds$primary")
      return(as.character(fs$primary))
    }
    warning("feature_sets.rds exists but $primary is missing or not length 33; using manual FEATURES33.")
  } else {
    warning("feature_sets.rds not found; using manual FEATURES33.")
  }
  MANUAL_FEATURES33
}

FEATURES33 <- load_primary_features()
stopifnot(length(FEATURES33) == 33L)

PREPROC_MATRIX_RDS <- file.path(DIR_MODEL, "X_primary33_std_mice.rds")
OUT_DIR <- file.path(DIR_OUTPUT, "qc_domain1_mice")
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

B_SIGCLUST      <- 200L      # raise to 500 for final run if desired
B_SIG_SUB       <- 200L
SIG_SUBSAMPLE_N <- c(2000L, 5000L, 10000L)
B_GAP           <- 100L      # raise to 200 for final run if desired
K_MAX_GAP       <- 15L
N_SUB_GAP       <- 5000L     # NA = full cohort; 5000 keeps runtime manageable
KM_NSTART_OBS   <- 50L
KM_NSTART_NULL  <- 10L
KM_ITERMAX      <- 100L
KM_ALGO         <- "Lloyd"

## ---------------- strict MICE matrix loader ----------------
load_feature_matrix <- function() {
  if (!file.exists(PREPROC_MATRIX_RDS)) {
    stop(
      "Missing MICE standardized primary matrix: ", PREPROC_MATRIX_RDS,
      "\nRun 23_mice_primary_pooling_v2_fixed.R or 23c_save_mice_matrix_labels.R first.",
      "\nThis strict script intentionally does NOT reconstruct a median-imputed matrix."
    )
  }

  message("Loading MICE standardized clustering matrix: ", PREPROC_MATRIX_RDS)
  Xdt <- as.data.table(readRDS(PREPROC_MATRIX_RDS))
  missing_features <- setdiff(FEATURES33, names(Xdt))
  if (length(missing_features)) {
    stop("X_primary33_std_mice.rds is missing features: ", paste(missing_features, collapse = ", "))
  }

  id_cols <- intersect(c("stay_id", "hadm_id", "subject_id"), names(Xdt))
  X <- as.matrix(Xdt[, ..FEATURES33])
  storage.mode(X) <- "double"

  if (anyNA(X)) {
    stop("MICE standardized matrix still contains NA values; do not run clusterability tests until fixed.")
  }
  if (!all(is.finite(X))) {
    stop("MICE standardized matrix contains non-finite values.")
  }

  means <- colMeans(X)
  sds <- apply(X, 2, sd)
  std_warn <- max(abs(means), na.rm = TRUE) > 0.05 || max(abs(sds - 1), na.rm = TRUE) > 0.05

  audit <- data.table(
    artifact = basename(PREPROC_MATRIX_RDS),
    path = PREPROC_MATRIX_RDS,
    n_patients = nrow(X),
    n_features = ncol(X),
    id_columns_present = paste(id_cols, collapse = ";"),
    max_abs_mean = max(abs(means), na.rm = TRUE),
    max_abs_sd_minus_1 = max(abs(sds - 1), na.rm = TRUE),
    standardized_check = ifelse(std_warn, "WARN", "OK"),
    feature_source = ifelse(file.exists(file.path(DIR_MODEL, "feature_sets.rds")),
                            "feature_sets.rds$primary", "manual FEATURES33")
  )
  fwrite(audit, file.path(OUT_DIR, "clusterability_mice_matrix_provenance.csv"))

  if (std_warn) {
    warning("MICE matrix does not look approximately standardized. See clusterability_mice_matrix_provenance.csv")
  }
  X
}

X <- load_feature_matrix()
N <- nrow(X)
D <- ncol(X)
message(sprintf("MICE feature matrix ready: %d patients x %d features", N, D))

## ---------------- helper: 2-means cluster index ----------------
cluster_index_2means <- function(mat, nstart) {
  km <- kmeans(mat, centers = 2, nstart = nstart, iter.max = KM_ITERMAX, algorithm = KM_ALGO)
  tot <- sum(sweep(mat, 2, colMeans(mat))^2)
  km$tot.withinss / tot
}

## ---------------- TEST 1: SigClust + effect size + sensitivity ----------------
run_sigclust <- function(mat, B) {
  ci_obs <- cluster_index_2means(mat, KM_NSTART_OBS)
  Sig <- cov(mat)
  mu <- colMeans(mat)
  ci_null <- numeric(B)
  for (b in seq_len(B)) {
    sim <- MASS::mvrnorm(nrow(mat), mu = mu, Sigma = Sig)
    ci_null[b] <- cluster_index_2means(sim, KM_NSTART_NULL)
  }
  nm <- mean(ci_null)
  nsd <- sd(ci_null)
  p <- (1 + sum(ci_null <= ci_obs)) / (B + 1)
  list(n = nrow(mat), ci_obs = ci_obs, null_mean = nm, null_sd = nsd,
       es_sd = (nm - ci_obs) / nsd, rel_pct = 100 * (nm - ci_obs) / nm,
       p = p, B = B)
}

message("Test 1/3: SigClust on full cohort ...")
sig <- run_sigclust(X, B_SIGCLUST)

message("Test 1b: SigClust subsample sensitivity ...")
sig_sens <- rbindlist(lapply(sort(unique(c(SIG_SUBSAMPLE_N, N))), function(nn) {
  if (nn >= N) {
    s <- sig
  } else {
    set.seed(1000 + nn)
    s <- run_sigclust(X[sample.int(N, nn), , drop = FALSE], B_SIG_SUB)
  }
  data.table(
    n = s$n,
    observed_CI = round(s$ci_obs, 4),
    null_mean = round(s$null_mean, 4),
    null_sd = signif(s$null_sd, 3),
    effect_size_SD = round(s$es_sd, 2),
    rel_effect_pct = round(s$rel_pct, 3),
    p_value = signif(s$p, 3),
    B = s$B
  )
}))

## ---------------- TEST 2: dip test (PCs + discriminant axis) ----------------
run_dip <- function(mat, n_pc = 5L) {
  pc <- prcomp(mat, center = TRUE, scale. = FALSE)
  projs <- setNames(lapply(seq_len(n_pc), function(i) pc$x[, i]), paste0("PC", seq_len(n_pc)))
  km <- kmeans(mat, 2, nstart = KM_NSTART_OBS, iter.max = KM_ITERMAX, algorithm = KM_ALGO)
  projs[["discriminant_axis"]] <- as.numeric(mat %*% (km$centers[1, ] - km$centers[2, ]))
  tab <- rbindlist(lapply(names(projs), function(nm) {
    dt <- diptest::dip.test(projs[[nm]])
    data.table(projection = nm, dip_stat = unname(dt$statistic), p_raw = dt$p.value)
  }))
  tab[, p_fdr := p.adjust(p_raw, "BH")][, multimodal_fdr05 := p_fdr < 0.05][]
}

message("Test 2/3: dip test ...")
dip_tab <- run_dip(X)

## ---------------- TEST 3: gap statistic, K.max=15 ----------------
run_gap <- function(mat, K.max, B, n_sub) {
  m <- mat
  if (!is.na(n_sub) && n_sub < nrow(mat)) {
    idx <- sample.int(nrow(mat), n_sub)
    m <- mat[idx, , drop = FALSE]
  }
  FUN <- function(x, k) kmeans(x, k, nstart = KM_NSTART_NULL, iter.max = KM_ITERMAX, algorithm = KM_ALGO)
  cg <- cluster::clusGap(m, FUNcluster = FUN, K.max = K.max, B = B, d.power = 2,
                         spaceH0 = "scaledPCA", verbose = FALSE)
  tab <- as.data.table(cg$Tab)[, k := seq_len(.N)]
  se <- cg$Tab[, "SE.sim"]
  g <- cg$Tab[, "gap"]
  list(
    tab = tab,
    n_used = nrow(m),
    gap_rising_to_kmax = as.logical(which.max(g) == K.max),
    k_firstSEmax = cluster::maxSE(g, se, "firstSEmax"),
    k_Tibs2001 = cluster::maxSE(g, se, "Tibs2001SEmax"),
    k_globalSEmax = cluster::maxSE(g, se, "globalSEmax")
  )
}

message("Test 3/3: gap statistic (K.max=", K_MAX_GAP, ") ...")
gap <- run_gap(X, K_MAX_GAP, B_GAP, N_SUB_GAP)

## ---------------- assemble / print / save ----------------
sig_row <- data.table(
  feature_set = "primary33_mice",
  test = "SigClust-like Gaussian null",
  n_patients = N,
  n_features = D,
  observed_cluster_index = round(sig$ci_obs, 4),
  null_mean = round(sig$null_mean, 4),
  null_sd = signif(sig$null_sd, 3),
  effect_size_SD = round(sig$es_sd, 2),
  rel_effect_pct = round(sig$rel_pct, 3),
  p_value = signif(sig$p, 3),
  B = sig$B
)

dip_axis_p <- dip_tab[projection == "discriminant_axis", p_fdr]
summary_tab <- data.table(
  feature_set = "primary33_mice",
  n_patients = N,
  n_features = D,
  matrix_artifact = basename(PREPROC_MATRIX_RDS),
  test = c(
    "Gap statistic (firstSEmax / Tibs2001 / globalSEmax)",
    "Dip test (PC1-5 + discriminant axis, BH-FDR)",
    "SigClust-like Gaussian null (+ effect size)"
  ),
  result = c(
    sprintf("K = %d / %d / %d (K.max=%d, d.power=2, scaledPCA, B=%d, n=%d); gap rises to K.max: %s",
            gap$k_firstSEmax, gap$k_Tibs2001, gap$k_globalSEmax,
            K_MAX_GAP, B_GAP, gap$n_used, gap$gap_rising_to_kmax),
    sprintf("%d of %d projections reject unimodality after BH-FDR (discriminant axis p_fdr=%.3g)",
            sum(dip_tab$multimodal_fdr05), nrow(dip_tab), dip_axis_p),
    sprintf("observed CI=%.4f; null=%.4f; effect=%.2f SD (%.2f%%); p=%.3g",
            sig$ci_obs, sig$null_mean, sig$es_sd, sig$rel_pct, sig$p)
  )
)

cat("\n================ CLUSTERABILITY SUMMARY (MICE strict) ================\n")
print(summary_tab)
cat("\n---- SigClust subsample sensitivity ----\n")
print(sig_sens)
cat("\n---- Dip test detail ----\n")
print(dip_tab)
cat("\n---- SigClust detail (full n) ----\n")
print(sig_row)
cat("\n---- Gap curve (K = 1..", K_MAX_GAP, ") ----\n", sep = "")
print(gap$tab)

fwrite(summary_tab, file.path(OUT_DIR, "clusterability_summary_v2.csv"))
fwrite(sig_sens,    file.path(OUT_DIR, "clusterability_sigclust_sensitivity.csv"))
fwrite(dip_tab,     file.path(OUT_DIR, "clusterability_dip_v2.csv"))
fwrite(sig_row,     file.path(OUT_DIR, "clusterability_sigclust_v2.csv"))
fwrite(gap$tab,     file.path(OUT_DIR, "clusterability_gap_curve_v2.csv"))
saveRDS(
  list(summary = summary_tab, sig = sig, sig_sensitivity = sig_sens,
       dip = dip_tab, gap = gap, N = N, D = D, features = FEATURES33,
       matrix_artifact = PREPROC_MATRIX_RDS),
  file.path(OUT_DIR, "clusterability_all_v2.rds")
)
message("Done. Strict MICE outputs written to: ", OUT_DIR)
