options(stringsAsFactors = FALSE, warn = 1)
arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
if (!length(arg)) stop("Cannot resolve runner path.")
runner <- normalizePath(sub("^--file=", "", arg[1]), winslash = "/", mustWork = TRUE)
D3R_SCRIPT_DIR <- dirname(runner)
source(file.path(D3R_SCRIPT_DIR, "41_d3r_sim_common_v1.R"))
source(file.path(D3R_SCRIPT_DIR, "41a_d3r_sim_freeze_spec_v1.R"))
source(file.path(D3R_SCRIPT_DIR, "41b_d3r_sim_execute_v1.R"))
source(file.path(D3R_SCRIPT_DIR, "41c_d3r_sim_postprocess_v1.R"))
source(file.path(D3R_SCRIPT_DIR, "41d_d3r_sim_independent_qc_v1.R"))
d3r_atomic_write_lines(capture.output(sessionInfo()), file.path(D3R_LOG_DIR, "sessionInfo.txt"), overwrite = TRUE)
d3r_msg("D3 regenerated-generator simulation completed: ", D3R_OUTPUT_ROOT)
