## ============================================================
## 10_table1_mice_local.R
## Generate Table 1 using MICE-primary K=2 labels
## Project: EHR audit MIMIC-IV / eICU transportability analysis
##
## Design:
##   - MIMIC labels: output/model/labels_primary_mice.rds
##   - eICU labels : output/eicu_cluster_labels_mice.csv
##   - C1 = cluster_k2 1 = higher-risk phenotype
##   - C2 = cluster_k2 2 = lower-risk phenotype
##   - Patient-level data are NOT exported unless WRITE_PATIENT_LEVEL <- TRUE.
## ============================================================

source(file.path(Sys.getenv("EHR_AUDIT_REPO_ROOT", unset = getwd()),
                 "R", "common", "00_paths.R"))

suppressPackageStartupMessages({
  library(data.table)
})

WRITE_PATIENT_LEVEL <- FALSE

QC_DIR  <- file.path(DIR_OUTPUT, "qc")
FIG_DIR <- file.path(DIR_OUTPUT, "fig")
dir.create(QC_DIR,  showWarnings = FALSE, recursive = TRUE)
dir.create(FIG_DIR, showWarnings = FALSE, recursive = TRUE)

## ---------- 1. Required files ----------
path_final_full <- PATH_FINAL_FULL
path_baseline   <- file.path(DIR_DATA, "baseline_covars.csv")
path_lab_mice   <- file.path(DIR_MODEL, "labels_primary_mice.rds")
path_x_mice     <- file.path(DIR_MODEL, "X_primary33_std_mice.rds")
path_sum_mice   <- file.path(QC_DIR, "mice_primary_label_summary.csv")
path_eicu       <- file.path(DIR_DATA, "eicu_external.csv")

## IMPORTANT: do not use old output/eicu_cluster_labels.csv.
## This file must be generated by 19_external_headtohead_mice_labels.R after adding the export block.
eicu_label_candidates <- c(
  file.path(DIR_OUTPUT, "eicu_cluster_labels_mice.csv"),
  file.path(QC_DIR, "eicu_cluster_labels_mice.csv")
)
path_eicu_lab <- eicu_label_candidates[file.exists(eicu_label_candidates)][1]

required <- data.table(
  item = c(
    "PATH_FINAL_FULL",
    "baseline_covars.csv",
    "labels_primary_mice.rds",
    "X_primary33_std_mice.rds",
    "mice_primary_label_summary.csv",
    "eicu_external.csv",
    "eicu_cluster_labels_mice.csv"
  ),
  path = c(
    path_final_full,
    path_baseline,
    path_lab_mice,
    path_x_mice,
    path_sum_mice,
    path_eicu,
    ifelse(is.na(path_eicu_lab), "", path_eicu_lab)
  )
)
required[, exists := file.exists(path)]
required[, size_MB := ifelse(exists, round(file.info(path)$size / 1024^2, 3), NA_real_)]
required[, modified_time := ifelse(exists, as.character(file.info(path)$mtime), NA_character_)]
print(required)
fwrite(required, file.path(QC_DIR, "table1_required_files_audit.csv"))

if (!file.exists(path_final_full)) stop("Missing PATH_FINAL_FULL: ", path_final_full)
if (!file.exists(path_baseline))   stop("Missing baseline_covars.csv: ", path_baseline)
if (!file.exists(path_lab_mice))   stop("Missing labels_primary_mice.rds: ", path_lab_mice)
if (!file.exists(path_x_mice))     stop("Missing X_primary33_std_mice.rds: ", path_x_mice)
if (!file.exists(path_sum_mice))   stop("Missing mice_primary_label_summary.csv: ", path_sum_mice)
if (!file.exists(path_eicu))       stop("Missing eicu_external.csv: ", path_eicu)
if (is.na(path_eicu_lab) || !file.exists(path_eicu_lab)) {
  stop(
    "Missing eICU MICE-label file. Required file: output/eicu_cluster_labels_mice.csv\n",
    "Run 19_external_headtohead_mice_labels.R after adding the eICU MICE-label export block, then rerun this script."
  )
}

## ---------- 2. Helper functions ----------
first_existing <- function(dt, candidates) {
  x <- intersect(candidates, names(dt))
  if (length(x) == 0) return(NA_character_)
  x[1]
}

vec_num <- function(dt, candidates) {
  cn <- first_existing(dt, candidates)
  if (is.na(cn)) return(rep(NA_real_, nrow(dt)))
  suppressWarnings(as.numeric(dt[[cn]]))
}

vec_chr <- function(dt, candidates) {
  cn <- first_existing(dt, candidates)
  if (is.na(cn)) return(rep(NA_character_, nrow(dt)))
  as.character(dt[[cn]])
}

parse_sex <- function(x) {
  if (is.numeric(x)) return(as.integer(x == 1))
  x <- toupper(trimws(as.character(x)))
  fifelse(x %in% c("1", "M", "MALE"), 1L,
          fifelse(x %in% c("0", "F", "FEMALE"), 0L, NA_integer_))
}

parse_binary <- function(x) {
  if (is.numeric(x)) return(as.integer(x == 1))
  x <- tolower(trimws(as.character(x)))
  fifelse(x %in% c("1", "yes", "y", "true", "t", "male"), 1L,
          fifelse(x %in% c("0", "no", "n", "false", "f", "female"), 0L, NA_integer_))
}

med_iqr <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  x <- x[is.finite(x)]
  if (length(x) == 0) return("—")
  q <- quantile(x, c(0.25, 0.50, 0.75), na.rm = TRUE, names = FALSE)
  sprintf("%.1f [%.1f, %.1f]", q[2], q[1], q[3])
}

n_pct <- function(x, positive = 1) {
  ok <- !is.na(x)
  if (!any(ok)) return("—")
  n <- sum(x[ok] == positive)
  d <- sum(ok)
  sprintf("%d (%.1f%%)", n, 100 * n / d)
}

safe_merge_one_to_one <- function(x, y, by, all.x = TRUE, name_y = "right table") {
  if (anyDuplicated(y[[by]]) > 0) stop("Duplicate IDs in ", name_y, ": ", by)
  merge(x, y, by = by, all.x = all.x)
}

## ---------- 3. MIMIC source frame ----------
ff  <- fread(path_final_full)
bc  <- fread(path_baseline)
lab <- as.data.table(readRDS(path_lab_mice))
X_mice <- as.data.table(readRDS(path_x_mice))
sum_mice <- fread(path_sum_mice)

id_mimic <- intersect(c("stay_id", "hadm_id", "subject_id"), names(ff))[1]
if (is.na(id_mimic)) stop("No valid ID column found in final_full.")
if (!id_mimic %in% names(bc))  stop("baseline_covars.csv does not contain ID column: ", id_mimic)
if (!id_mimic %in% names(lab)) stop("labels_primary_mice.rds does not contain ID column: ", id_mimic)
if (!id_mimic %in% names(X_mice)) stop("X_primary33_std_mice.rds does not contain ID column: ", id_mimic)
if (!"cluster_k2" %in% names(lab)) stop("labels_primary_mice.rds does not contain cluster_k2.")

if (anyDuplicated(ff[[id_mimic]]) > 0) stop("Duplicate IDs in final_full.")
if (anyDuplicated(lab[[id_mimic]]) > 0) stop("Duplicate IDs in labels_primary_mice.rds.")
if (anyDuplicated(X_mice[[id_mimic]]) > 0) stop("Duplicate IDs in X_primary33_std_mice.rds.")

## Merge baseline columns not already present in final_full.
bc_cols_to_add <- setdiff(names(bc), names(ff))
bc_use_cols <- unique(c(id_mimic, bc_cols_to_add))
M <- safe_merge_one_to_one(ff, bc[, ..bc_use_cols], by = id_mimic, all.x = TRUE, name_y = "baseline_covars.csv")
M <- safe_merge_one_to_one(M, lab[, .SD, .SDcols = c(id_mimic, "cluster_k2")], by = id_mimic, all.x = TRUE, name_y = "labels_primary_mice.rds")

n_missing_mimic_label <- sum(is.na(M$cluster_k2))
if (n_missing_mimic_label > 0) stop("Missing MICE labels after MIMIC merge: ", n_missing_mimic_label)

M[, cluster_k2 := as.integer(cluster_k2)]
M[, cohort := "MIMIC-IV"]
M[, phenotype := fifelse(cluster_k2 == 1L, "C1 higher-risk", "C2 lower-risk")]

Mtab <- data.table(
  cohort = M$cohort,
  phenotype = M$phenotype,
  cluster_k2 = M$cluster_k2,
  age = vec_num(M, c("age", "anchor_age")),
  male = parse_sex(vec_chr(M, c("gender", "sex"))),
  charlson_comorbidity_index = vec_num(M, c(
    "charlson_comorbidity_index", "charlson", "charlson_index"
  )),
  sapsii = vec_num(M, c("sapsii", "saps_ii")),
  sofa_score = vec_num(M, c("sofa_score", "sofa")),
  aki_stage_0_24h = vec_num(M, c("aki_stage_0_24h", "aki_stage")),
  mechanical_ventilation = parse_binary(vec_chr(M, c(
    "mechanical_ventilation", "mechanical_ventilation_24h",
    "ventilation", "vent_24h", "mech_vent", "vent_0_24h"
  ))),
  vasopressor = parse_binary(vec_chr(M, c(
    "vasopressor", "vasopressor_use", "vasopressor_24h",
    "vaso", "vaso_24h", "vaso_0_24h"
  ))),
  lactate_max = vec_num(M, c("lactate_max")),
  creatinine_max = vec_num(M, c("creatinine_max", "scr_max")),
  bun_max = vec_num(M, c("bun_max")),
  urine_output_24h_ml = vec_num(M, c("urine_output_24h_ml", "uo_24h", "urineoutput_24h")),
  pao2fio2ratio_min = vec_num(M, c("pao2fio2ratio_min", "pafi_min")),
  platelets_min = vec_num(M, c("platelets_min", "platelet_min")),
  bicarbonate_min = vec_num(M, c("bicarbonate_min")),
  gcs_min = vec_num(M, c("gcs_min")),
  hospital_mortality = vec_num(M, c("hospital_mortality", "hosp_mortality")),
  mortality_30d = vec_num(M, c("mortality_30d", "death_30d")),
  make30 = vec_num(M, c("make30", "MAKE30")),
  make_hosp = rep(NA_real_, nrow(M))
)

## ---------- 4. eICU source frame ----------
E <- fread(path_eicu)
Elab <- fread(path_eicu_lab)

id_eicu <- intersect(
  c("patientunitstayid", "stay_id", "hadm_id", "subject_id", "uniquepid"),
  intersect(names(E), names(Elab))
)[1]
if (is.na(id_eicu)) {
  cat("eICU columns:\n"); print(names(E))
  cat("eICU label columns:\n"); print(names(Elab))
  stop("Cannot identify a shared eICU ID column.")
}

label_col_eicu <- intersect(c("cluster_k2", "phenotype", "cluster", "eicu_cluster", "label"), names(Elab))[1]
if (is.na(label_col_eicu)) stop("Cannot identify cluster label column in eICU label file: ", path_eicu_lab)
setnames(Elab, label_col_eicu, "cluster_k2", skip_absent = TRUE)
Elab[, cluster_k2 := as.integer(as.character(cluster_k2))]

if (anyDuplicated(Elab[[id_eicu]]) > 0) stop("Duplicate IDs in eICU label file.")

## Bring label plus outcome variables from label file only if eICU source lacks them.
elab_cols <- c(id_eicu, "cluster_k2")
for (v in c("hosp_mortality", "hospital_mortality", "make_hosp", "label_source")) {
  if (v %in% names(Elab) && !v %in% names(E)) elab_cols <- c(elab_cols, v)
}
elab_cols <- unique(elab_cols)

E <- safe_merge_one_to_one(E, Elab[, ..elab_cols], by = id_eicu, all.x = TRUE, name_y = "eicu_cluster_labels_mice.csv")

n_miss_eicu_label <- sum(is.na(E$cluster_k2))
if (n_miss_eicu_label > 0) {
  warning("Dropping eICU rows without MICE-derived K2 labels: ", n_miss_eicu_label)
  ## This local-only file is disabled by default to avoid patient-level export.
  if (WRITE_PATIENT_LEVEL) {
    fwrite(E[is.na(cluster_k2)], file.path(QC_DIR, "table1_eicu_rows_without_mice_label_LOCAL_ONLY.csv"))
  }
  E <- E[!is.na(cluster_k2)]
}

E[, cluster_k2 := as.integer(cluster_k2)]
E[, cohort := "eICU"]
E[, phenotype := fifelse(cluster_k2 == 1L, "C1 higher-risk", "C2 lower-risk")]

## Derive eICU in-hospital MAKE approximation if needed.
make_hosp_vec <- vec_num(E, c("make_hosp"))
if (all(is.na(make_hosp_vec))) {
  hm <- vec_num(E, c("hosp_mortality", "hospital_mortality"))
  scr_dis <- vec_num(E, c("scr_discharge", "creatinine_discharge", "creatinine_discharge_max"))
  scr_base <- vec_num(E, c("scr_baseline", "baseline_creatinine", "creatinine_baseline"))
  if (all(is.na(scr_dis)) || all(is.na(scr_base))) {
    make_hosp_vec <- hm
  } else {
    make_hosp_vec <- as.integer(hm == 1 | (!is.na(scr_dis) & !is.na(scr_base) & scr_dis >= 1.5 * scr_base))
  }
}

Etab <- data.table(
  cohort = E$cohort,
  phenotype = E$phenotype,
  cluster_k2 = E$cluster_k2,
  age = vec_num(E, c("age", "anchor_age")),
  male = parse_sex(vec_chr(E, c("sex", "gender"))),
  charlson_comorbidity_index = vec_num(E, c(
    "charlson_comorbidity_index", "charlson", "charlson_index"
  )),
  sapsii = vec_num(E, c("sapsii", "saps_ii")),
  sofa_score = vec_num(E, c("sofa_score", "sofa")),
  aki_stage_0_24h = vec_num(E, c("aki_stage_0_24h", "aki_stage")),
  mechanical_ventilation = parse_binary(vec_chr(E, c(
    "mechanical_ventilation", "mechanical_ventilation_24h",
    "ventilation", "vent_24h", "mech_vent", "vent_0_24h"
  ))),
  vasopressor = parse_binary(vec_chr(E, c(
    "vasopressor", "vasopressor_use", "vasopressor_24h",
    "vaso", "vaso_24h", "vaso_0_24h"
  ))),
  lactate_max = vec_num(E, c("lactate_max", "lactate")),
  creatinine_max = vec_num(E, c("creatinine_max", "creatinine", "scr_max")),
  bun_max = vec_num(E, c("bun_max", "bun")),
  urine_output_24h_ml = vec_num(E, c("urine_output_24h_ml", "urineoutput_24h", "urine_output", "uo_24h")),
  pao2fio2ratio_min = vec_num(E, c("pao2fio2ratio_min", "pao2fio2ratio", "pafi_min")),
  platelets_min = vec_num(E, c("platelets_min", "platelets", "platelet_min")),
  bicarbonate_min = vec_num(E, c("bicarbonate_min", "bicarbonate")),
  gcs_min = vec_num(E, c("gcs_min", "gcs")),
  hospital_mortality = vec_num(E, c("hosp_mortality", "hospital_mortality")),
  mortality_30d = rep(NA_real_, nrow(E)),
  make30 = rep(NA_real_, nrow(E)),
  make_hosp = make_hosp_vec
)

D <- rbindlist(list(Mtab, Etab), fill = TRUE)
D[, group := paste(cohort, phenotype)]
group_levels <- c(
  "MIMIC-IV C1 higher-risk",
  "MIMIC-IV C2 lower-risk",
  "eICU C1 higher-risk",
  "eICU C2 lower-risk"
)
D[, group := factor(group, levels = group_levels)]

## ---------- 5. Generate Table 1 ----------
cont_rows <- data.table(
  section = c(
    "Demographics", "Comorbidity", "Illness severity", "Illness severity",
    "Representative first-24h physiology",
    "Representative first-24h physiology", "Representative first-24h physiology",
    "Representative first-24h physiology", "Representative first-24h physiology",
    "Representative first-24h physiology", "Representative first-24h physiology",
    "Representative first-24h physiology"
  ),
  characteristic = c(
    "Age, years",
    "Charlson Comorbidity Index",
    "SAPS II",
    "SOFA score",
    "Lactate, mmol/L",
    "Serum creatinine, mg/dL",
    "Blood urea nitrogen, mg/dL",
    "24-hour urine output, mL",
    "PaO2/FiO2 ratio",
    "Platelet count, ×10^9/L",
    "Bicarbonate, mmol/L",
    "Glasgow Coma Scale"
  ),
  var = c(
    "age", "charlson_comorbidity_index", "sapsii", "sofa_score",
    "lactate_max", "creatinine_max", "bun_max",
    "urine_output_24h_ml", "pao2fio2ratio_min", "platelets_min",
    "bicarbonate_min", "gcs_min"
  )
)

bin_rows <- data.table(
  section = c(
    "Demographics", "Organ support", "Organ support",
    "Outcomes", "Outcomes", "Outcomes", "Outcomes"
  ),
  characteristic = c(
    "Male sex",
    "Mechanical ventilation",
    "Vasopressor use",
    "In-hospital mortality",
    "30-day mortality",
    "MAKE-30",
    "In-hospital MAKE approximation"
  ),
  var = c(
    "male", "mechanical_ventilation", "vasopressor",
    "hospital_mortality", "mortality_30d", "make30", "make_hosp"
  )
)

make_cont_summary <- function(var, section, characteristic) {
  out <- D[, .(value = med_iqr(get(var))), by = group]
  out[, `:=`(section = section, characteristic = characteristic)]
  out
}

make_bin_summary <- function(var, section, characteristic) {
  out <- D[, .(value = n_pct(get(var), 1)), by = group]
  out[, `:=`(section = section, characteristic = characteristic)]
  out
}

nrow_tab <- D[, .(value = as.character(.N)), by = group]
nrow_tab[, `:=`(section = "Cohort size", characteristic = "Patients, n")]

tab_long <- rbindlist(list(
  nrow_tab,
  rbindlist(lapply(seq_len(nrow(cont_rows)), function(i) {
    make_cont_summary(cont_rows$var[i], cont_rows$section[i], cont_rows$characteristic[i])
  })),
  rbindlist(lapply(seq_len(nrow(bin_rows)), function(i) {
    make_bin_summary(bin_rows$var[i], bin_rows$section[i], bin_rows$characteristic[i])
  }))
), fill = TRUE)

aki_vals <- sort(unique(na.omit(D$aki_stage_0_24h)))
if (length(aki_vals) > 0) {
  aki_stage_rows <- rbindlist(lapply(aki_vals, function(s) {
    tmp <- D[, .(value = n_pct(as.integer(aki_stage_0_24h == s), 1)), by = group]
    tmp[, `:=`(
      section = "Illness severity",
      characteristic = paste0("AKI stage ", s)
    )]
    tmp
  }), fill = TRUE)
  tab_long <- rbindlist(list(tab_long, aki_stage_rows), fill = TRUE)
}

## Add nonmissing counts for auditing, not for main display.
audit_vars <- unique(c(cont_rows$var, bin_rows$var, "aki_stage_0_24h"))
missing_audit <- rbindlist(lapply(audit_vars, function(v) {
  D[, .(
    n = .N,
    n_nonmissing = sum(!is.na(get(v))),
    n_missing = sum(is.na(get(v))),
    pct_missing = round(100 * mean(is.na(get(v))), 2)
  ), by = .(cohort, phenotype, cluster_k2)][, variable := v]
}), fill = TRUE)
setcolorder(missing_audit, c("variable", "cohort", "phenotype", "cluster_k2", "n", "n_nonmissing", "n_missing", "pct_missing"))
fwrite(missing_audit, file.path(QC_DIR, "table1_variable_missingness_audit.csv"))

tab_wide <- dcast(tab_long, section + characteristic ~ group, value.var = "value")
setcolorder(tab_wide, c("section", "characteristic", intersect(group_levels, names(tab_wide))))
fwrite(tab_wide, file.path(QC_DIR, "table1_mimic_eicu_by_mice_subphenotype.csv"))
fwrite(tab_long, file.path(QC_DIR, "table1_mimic_eicu_by_mice_subphenotype_long.csv"))

## ---------- 6. Label distribution and provenance ----------
label_dist <- D[, .N, by = .(cohort, phenotype, cluster_k2)]
label_dist[, pct := round(100 * N / sum(N), 2), by = cohort]
setorder(label_dist, cohort, cluster_k2)
fwrite(label_dist, file.path(QC_DIR, "table1_label_distribution_mice.csv"))

mimic_label_summary <- lab[, .N, by = cluster_k2][order(cluster_k2)]
eicu_label_summary <- Elab[, .N, by = cluster_k2][order(cluster_k2)]

prov <- rbindlist(list(
  data.table(
    item = "MIMIC label source",
    source_file = path_lab_mice,
    exists = file.exists(path_lab_mice),
    n_rows = nrow(lab),
    id_column = id_mimic,
    label_column = "cluster_k2",
    n_C1 = mimic_label_summary[cluster_k2 == 1, N],
    n_C2 = mimic_label_summary[cluster_k2 == 2, N],
    note = "cluster_k2=1 is higher-risk phenotype according to mice_primary_label_summary.csv"
  ),
  data.table(
    item = "MIMIC matrix source",
    source_file = path_x_mice,
    exists = file.exists(path_x_mice),
    n_rows = nrow(X_mice),
    id_column = id_mimic,
    label_column = "",
    n_C1 = NA_integer_,
    n_C2 = NA_integer_,
    note = "MICE-primary standardized 33-feature matrix with ID column"
  ),
  data.table(
    item = "eICU label source",
    source_file = path_eicu_lab,
    exists = file.exists(path_eicu_lab),
    n_rows = nrow(Elab),
    id_column = id_eicu,
    label_column = "cluster_k2",
    n_C1 = eicu_label_summary[cluster_k2 == 1, N],
    n_C2 = eicu_label_summary[cluster_k2 == 2, N],
    note = "Generated by modified 19 script using MICE-primary label system"
  )
), fill = TRUE)

fwrite(prov, file.path(QC_DIR, "table1_label_provenance.csv"))

## ---------- 7. Optional DOCX export ----------
if (requireNamespace("officer", quietly = TRUE) && requireNamespace("flextable", quietly = TRUE)) {
  ft <- flextable::flextable(tab_wide)
  ft <- flextable::theme_booktabs(ft)
  ft <- flextable::autofit(ft)
  ft <- flextable::set_caption(
    ft,
    caption = "Table 1. Baseline characteristics by MICE-primary K=2 subphenotype in MIMIC-IV and eICU."
  )

  note_text <- "Values are median [IQR] or n (%). C1 denotes the higher-risk phenotype; C2 denotes the lower-risk phenotype. MIMIC labels are from labels_primary_mice.rds, and eICU labels are from eicu_cluster_labels_mice.csv."

  doc <- officer::read_docx()
  doc <- officer::body_add_par(
    doc,
    "Table 1. Baseline characteristics by MICE-primary K=2 subphenotype in MIMIC-IV and eICU.",
    style = "heading 1"
  )
  doc <- flextable::body_add_flextable(doc, value = ft)
  doc <- officer::body_add_par(doc, note_text, style = "Normal")
  print(doc, target = file.path(QC_DIR, "table1_mimic_eicu_by_mice_subphenotype.docx"))
} else {
  message("Packages officer/flextable not installed; DOCX export skipped. CSV was generated.")
  message("To enable DOCX export: install.packages(c('officer','flextable'))")
}

## ---------- 8. Optional patient-level export ----------
if (WRITE_PATIENT_LEVEL) {
  fwrite(D, file.path(QC_DIR, "table1_patient_level_frame_LOCAL_ONLY.csv"))
}

## ---------- 9. Final sanity checks ----------
cat("\n===== Table 1 label distribution =====\n")
print(label_dist)

cat("\n===== Table 1 provenance =====\n")
print(prov)

cat("\nFinished Table 1 generation. Outputs:\n")
cat(" - ", file.path(QC_DIR, "table1_mimic_eicu_by_mice_subphenotype.csv"), "\n", sep = "")
cat(" - ", file.path(QC_DIR, "table1_mimic_eicu_by_mice_subphenotype_long.csv"), "\n", sep = "")
cat(" - ", file.path(QC_DIR, "table1_label_distribution_mice.csv"), "\n", sep = "")
cat(" - ", file.path(QC_DIR, "table1_label_provenance.csv"), "\n", sep = "")
cat(" - ", file.path(QC_DIR, "table1_variable_missingness_audit.csv"), "\n", sep = "")
cat(" - ", file.path(QC_DIR, "table1_required_files_audit.csv"), "\n", sep = "")
